// Generated by gencpp from file duckietown_msgs/WheelsCmdStamped.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_WHEELSCMDSTAMPED_H
#define DUCKIETOWN_MSGS_MESSAGE_WHEELSCMDSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace duckietown_msgs
{
template <class ContainerAllocator>
struct WheelsCmdStamped_
{
  typedef WheelsCmdStamped_<ContainerAllocator> Type;

  WheelsCmdStamped_()
    : header()
    , vel_left(0.0)
    , vel_right(0.0)  {
    }
  WheelsCmdStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vel_left(0.0)
    , vel_right(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _vel_left_type;
  _vel_left_type vel_left;

   typedef float _vel_right_type;
  _vel_right_type vel_right;





  typedef boost::shared_ptr< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> const> ConstPtr;

}; // struct WheelsCmdStamped_

typedef ::duckietown_msgs::WheelsCmdStamped_<std::allocator<void> > WheelsCmdStamped;

typedef boost::shared_ptr< ::duckietown_msgs::WheelsCmdStamped > WheelsCmdStampedPtr;
typedef boost::shared_ptr< ::duckietown_msgs::WheelsCmdStamped const> WheelsCmdStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'duckietown_msgs': ['/duckietown/dt_msg_ws/src/duckietown_msgs/msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edbf8d24194d839b1982a6a991b552c6";
  }

  static const char* value(const ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xedbf8d24194d839bULL;
  static const uint64_t static_value2 = 0x1982a6a991b552c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/WheelsCmdStamped";
  }

  static const char* value(const ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 vel_left\n"
"float32 vel_right\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vel_left);
      stream.next(m.vel_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelsCmdStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::WheelsCmdStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vel_left: ";
    Printer<float>::stream(s, indent + "  ", v.vel_left);
    s << indent << "vel_right: ";
    Printer<float>::stream(s, indent + "  ", v.vel_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_WHEELSCMDSTAMPED_H
